accounts/urls.py
from django.urls import path

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    # ex: /accounts/signup/
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

concierge/urls.py
from django.urls import path

from . import views

app_name = 'concierge'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:location_name>/', views.swipe, name='swipe'),
    path(
        'choice_location/<str:prefecture>/',
        views.choice_location, name='choice_location'),
    path(
        'choice_location/<str:prefecture>/<str:region>/',
        views.choice_location, name='choice_location'),
    path(
        'choice_location/<str:prefecture>/<str:region>/<str:district>/',
        views.choice_location, name='choice_location'),
    path(
        'choice_location/<str:prefecture>/<str:region>/<str:district>/<str:station>/',
        views.choice_location, name='choice_location'),
    path(
        'swipe/<str:prefecture>/',
        views.swipe, name='swipe'),
    path(
        'swipe/<str:prefecture>/<str:region>/',
        views.swipe, name='swipe'),
    path(
        'swipe/<str:prefecture>/<str:region>/<str:district>/',
        views.swipe, name='swipe'),
    path(
        'swipe/<str:prefecture>/<str:region>/<str:district>/<str:station>/',
        views.swipe, name='swipe'),
]

nanitabe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('concierge/', include('concierge.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('concierge.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

concierge/models.py
from django.db import models
# Create your models here.


class Location(models.Model):
    # 場所の名前（日本語）
    name = models.CharField(max_length=128)
    # 地域のURL
    prefecture = models.CharField(max_length=64, blank=True, null=True)
    region = models.CharField(max_length=64, blank=True, null=True)
    district = models.CharField(max_length=64, blank=True, null=True)
    station = models.CharField(max_length=64, blank=True, null=True)
    # 地域の階層（県、地区、駅など）
    level = models.CharField(max_length=64, blank=True, null=True)
    # urlを連結した文字列
    url = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name


class Genre(models.Model):
    location_name = models.CharField(max_length=128)
    name = models.CharField(max_length=128)
    url = models.CharField(max_length=128)
    saved_date = models.DateTimeField()

    def __str__(self):
        return self.location_name + ' ' + self.name


class Shop(models.Model):
    location_name = models.CharField(max_length=128)
    genre_name = models.CharField(max_length=128)
    name = models.CharField(max_length=128)
    url = models.CharField(max_length=128)
    img_url = models.CharField(max_length=256)
    rank = models.IntegerField()
    rate = models.FloatField()
    is_day = models.BooleanField()
    saved_date = models.DateTimeField()

    def __str__(self):
        return self.location_name + ' ' + self.genre_name + ' ' + self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

concierge/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, get_list_or_404
from django.http import HttpResponse

import random
import os
from django.utils import timezone
# Create your views here.
from .models import Location, Genre, Shop
from .modules import choice_shop

HOME_URL = 'https://tabelog.com/'


def index(request):
    locations = Location.objects.all()
    loc_top_00 = Location.objects.get(name='渋谷')
    loc_top_01 = Location.objects.get(name='新宿')
    # loc_tokyo = Location.objects.get(name='東京')
    loc_top_list = [loc_top_00, loc_top_01]
    return render(
        request,
        'concierge/index.html',
        {
            'loc_top_list': loc_top_list,
            'user': request.user})


def swipe(
        request, prefecture=None, region=None, district=None, station=None):
    area_str_list = ['prefecture', 'region', 'district', 'station']
    area_list = [prefecture, region, district, station]
    area_dict = dict(zip(area_str_list, area_list))
    location = get_object_or_404(Location, **area_dict)
    # ジャンルのリストを抽出。DBにないならスクレイピング。
    # genreの情報が古くなったら更新する機能をつけたい
    genre_list = Genre.objects.filter(location_name=location.name)
    if len(genre_list) == 0:
        # url_list = []
        # for area_url in area_list:
        #     if area_url is not None:
        #         url_list.append(area_url)
        # location.url = os.path.join(HOME_URL, *url_list) + '/'
        genre_dict = choice_shop.get_genre_dict(
            os.path.join(HOME_URL, location.url))
        for genre_url, genre_name in genre_dict.items():
            genre, created = Genre.objects.get_or_create(
                location_name=location.name,
                name=genre_name,
                url=genre_url,
                saved_date=timezone.now(),
            )
        genre_list = Genre.objects.filter(location_name=location.name)
    genre = random.choice(genre_list)
    shop_list = Shop.objects.filter(
        location_name=location.name, genre_name=genre.name)
    if len(shop_list) == 0:
        shop_dcit = choice_shop.get_shops_dict(genre.url)
        for shop_url, shop_elem_dict in shop_dcit.items():
            shop, created = Shop.objects.get_or_create(
                location_name=location.name,
                genre_name=genre.name,
                name=shop_elem_dict['nm'],
                url=shop_url,
                img_url=shop_elem_dict['img_url'],
                rank=shop_elem_dict['rank'],
                rate=shop_elem_dict['rate'],
                is_day=True,
                saved_date=timezone.now(),
            )
        shop_list = Shop.objects.filter(
            location_name=location.name, genre_name=genre.name)
    shop = random.choice(shop_list)
    return render(
        request, 'concierge/swipe.html', {
            'location': location,
            'genre': genre,
            'shop': shop, })


def choice_location(
        request, prefecture=None, region=None, district=None, station=None):
    """
    parent_locationをクリックしたらswipeの画面に移動
    child_locationをクリックしたらより詳細な地域を選択する画面に移動
    ただし、child_locationが一つもなかった場合はswipe画面に移動
    """
    area_str_list = ['prefecture', 'region', 'district', 'station']

    parent_area_list = [prefecture, region, district, station]
    parent_area_dict = dict(zip(area_str_list, parent_area_list))
    parent_location = get_object_or_404(Location, **parent_area_dict)
    # parent_url_list = []
    # for area in area_str_list:
    #     if parent_area_dict[area] is not None:
    #         parent_url_list.append(
    #             getattr(parent_location, area))
    # parent_location.url = os.path.join(*parent_url_list)

    child_area_dict = {}
    for key, value in parent_area_dict.items():
        if value is not None:
            child_area_dict[key] = value
    # これ以上child_locationがない場合はparent_locationのswipe画面に移動
    if len(child_area_dict) >= len(area_str_list):
        return redirect(
            os.path.join('/concierge/swipe/', parent_location.url))

    child_area_dict['level'] = area_str_list[len(child_area_dict)]
    child_locations = list(Location.objects.filter(**child_area_dict))
    print(child_locations, type(child_locations))

    # child_locationが一つもなかった場合はparent_locationのswipe画面に移動
    if len(child_locations) == 0:
        return redirect(
            os.path.join('/concierge/swipe/', parent_location.url))
    # 詳細な地域選択画面に移動
    for child_location in child_locations:
        url_ = []
        for i in range(len(child_area_dict)):
            url_.append(getattr(child_location, area_str_list[i]))
        child_location.url = os.path.join(*url_)
    return render(
        request, 'concierge/choice_location.html',
        {
            'user': request.user,
            'parent_location': parent_location,
            'child_locations': child_locations,
        }
    )

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}

concierge/templates/concierge/choice_location.html
{% load static %}
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <div>
            <h1><a href="/concierge/">ナニ食べ</a></h1>
            <p>{{ user.username }}</p>
            <a href="{% url 'logout' %}">Log out</a>
        </div>
        <p>{{ parent_location.name }}</p>
        <a href='/concierge/swipe/{{ parent_location.url }}' target="_brank">
            {{ parent_location.name }}
        </a>


        {% for child_location in child_locations %}
            <a href='/concierge/choice_location/{{ child_location.url }}'>
                <p>{{ child_location.name }}</p>
            </a>
        {% endfor %}
    </body>
</html>

concierge/templates/concierge/index.html
{% load static %}
<html>
    <head>
        <title>nanitabe</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <div>
            <h1><a href="/concierge/">ナニ食べ</a></h1>
            <p>{{ user.username }}</p>
            <a href="{% url 'logout' %}">Log out</a>
        </div>


        {% for location in loc_top_list %}
            <a href='/concierge/choice_location/{{ location.url }}'>
                <p>{{ location.name }}</p>
            </a>
        {% endfor %}
        <a href='/concierge/choice_location/tokyo/'>
            <p>違う場所から探す</p>
        </a>
    </body>
</html>

concierge/templates/concierge/swipe.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>なん食べる？</title>
    </head>
</html>
<body>
    <p>{{ location.name }}</p>
    <h1><a href="/concierge/">ナニ食べ</a></h1>
    <h2>{{ genre.name }}</h2>
    <p>{{ shop.name }}</p>
    <a href={{ shop.url }} target="_brank">
        <img src={{ shop.img_url }} width="150" height="150" alt={{ shop.name }}>
    </a>
    <a href='/concierge/swipe/{{ location.url }}'>
        リロード
    </a>
</body>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Blog App with Auth | Django2 Tutorial</title>
</head>
<body>
<div class="container">
    <header>
        <p class="site-name"><a href="{% url 'concierge:index' %}">Blog App</a></p>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}" class="signup">Sign up</a></li>
                <li><a href="{% url 'login' %}" class="login">Login</a></li>
                {% endif %}
                <li><a href="{% url 'concierge:index' %}" class="act">tmp tmp</a></li>
            </ul>
        </nav>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>